:toc:

== overview

this is an experimental repo which uses Rust to build UIs for Holochain, and features a `wasm-bindgen` FFI binding library to the https://github.com/holochain/holochain-client-js[holochain-client-js] library.

== 🛑 note about abandonment 🛑

this repo is abandoned. as of 2022-10-26 I am leaving Neighbourhoods, and the remaining team has no plans (and insufficient Rust skill) to move this effort forwards.

Holochain, additionally, does not make it easy to write Rust frontends, even though in theory they could make it quite easy, and aim for type coherence across backend+frontend, because the entirety of Holochain's backend is written in Rust.

because then only official frontend client for Holochain is written in Javascript, all of the types which are defined in the backend, in Rust, are not available for frontend clients.

imo this is bad, especially when one considers that if the official frontend client were written in Rust, it would get type coherence "for free" and a Javascript wrapper could be exposed via https://rustwasm.github.io/wasm-bindgen/[wasm-bindgen]. additionally, the (inevitable and unavoidable) problems of synchronizing two halves of a codebase which are written in 2 different languages which cannot "talk to" each other could be avoided.

this means that all changes to Holochain's backend going forwards (which at their current rate of change might be quite a lot) could silently break the frontend client, and manual programmer-eyes will have to go scan over it to check for consistency.

if a Rust client were used, and proper CI discipline put in place, those checks would be caught statically, or would perhaps "automatically work" if the API types were changed in a way that still de/serialized properly.

I believe it is the correct decision for Neighbourhoods to abandon this & the https://github.com/mhuesch/holochain_client_wrapper[holochain_client_wrapper] effort. because it is swimming upstream against the current of Holochain, which wants to take the "path of short-term least resistance" and use Javascript as default. I (@mhuesch) put a lot of work into this Rust effort, and am bummed out to see it die, but believe that Holochain is too shaky of a foundation to build anything real on at this stage.

that is why I am taking my energies to https://urbit.org/[Urbit].

== initial repo setup

=== init submodules

[source]
----
git submodule update --init
----

== Nix setup

install a https://nixos.wiki/wiki/Flakes#Installing_flakes[Flakes] supporting https://nixos.org/download.html[`nix`]

edit `/etc/nix/nix.conf` to include the following:

----
experimental-features = nix-command flakes
----

optionally (but strongly suggested because it will dramatically speed up first-build times), also add these lines to `nix.conf` in order to enable the Holochain binary caches.
public keys can be checked at the substituter URLs.

----
substituters = https://cache.nixos.org/ https://cache.holo.host/ https://holochain-ci.cachix.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.holo.host-1:lNXIXtJgS9Iuw4Cu6X0HINLu9sTfcjEntnrgwMQIMcE= cache.holo.host-2:ZJCkX3AUYZ8soxTLfTb60g+F3MkWD7hkH9y8CgqwhDQ= holochain-ci.cachix.org-1:5IUSkZc0aoRS53rfkvH9Kid40NpyjwCMCzwRTXy+QN8=
----

== building

prequisite: follow 'Nix setup' above.

[source]
----
# enter dev shell (we need impure because Holonix is not pure 😢)
$ nix develop --impure
[<...>]$ npm install
[<...>]$ npm run hc:build
[<...>]$ npm run hc:pack
[<...>]$ npm run hc:mk-sensemaker # this may take a while to run
----

== running

[source]
----
# in dev shell
[<...>]$ npm run hc:run
----
